# Generated by Django 5.1.3 on 2024-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_register_remove_customuser_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='product',
        ),
        migrations.AlterField(
            model_name='product_img',
            name='rasm',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
